# Generated by Django 4.1.6 on 2023-02-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('imgs', models.ImageField(blank=True, upload_to='venues_pics')),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('lng', models.DecimalField(decimal_places=14, max_digits=17)),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17)),
            ],
        ),
    ]
