# Generated by Django 4.1.6 on 2023-02-08 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='imgs',
        ),
        migrations.CreateModel(
            name='VenuePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='venue_pics')),
                ('order', models.SmallIntegerField(max_length=100, verbose_name='Volume Number')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.venue')),
            ],
            options={
                'unique_together': {('venue', 'order')},
            },
        ),
    ]
