# Generated by Django 4.1.6 on 2023-03-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_venue_imgs_venuephoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venuephoto',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='venuephoto',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Order #'),
        ),
    ]
