# Generated by Django 4.1.6 on 2023-05-13 13:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_venuephoto_options_alter_venuephoto_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description_short',
            field=models.CharField(blank=True, max_length=200, verbose_name='Short description'),
        ),
    ]
