# Generated by Django 4.1.6 on 2023-05-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_venue_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuephoto',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.venue'),
        ),
    ]
