# Generated by Django 4.1.6 on 2023-05-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_venuephoto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Short description'),
        ),
    ]
