# Generated by Django 4.1.6 on 2023-05-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_venue_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuephoto',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.venue'),
        ),
    ]
