# Generated by Django 4.1.6 on 2023-05-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_venuephoto_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
