# Generated by Django 4.1.6 on 2023-05-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_venue_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuephoto',
            name='image',
            field=models.ImageField(default='https://placehold.co/600x400.png', upload_to='venue_pics'),
            preserve_default=False,
        ),
    ]
